### ISSUE TITLE
INI config file format

### ISSUE THREAD

**Issue by BrandonLMorris** [orlandoacevedo/MCGPU#34]
Modify the config files to use the [INI](https://en.wikipedia.org/wiki/INI_file) format.

This would allow a lot more flexibility and extensibility to the way configuration files are structured. Existing config files and the method of generating/reading them for tests will need to be modified.

An example config file might look like
```
# Simulation box size (in angstroms)
x=55
y=55
z=55

# Temperature (in Kelvin)
temp=298.5

max-translation=0.15
steps=1000
...
```

**Comment by joverbey** [comment]
@orlandoacevedo How would you feel about this?

It should only take a day or so for Brandon to make the change, if you want to do it.

**Comment by orlandoacevedo** [comment]
I'm fine with making this change.
